/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BulletinEntity;
import java.util.ArrayList;
import java.util.List;

/**
 * ControllerBulletinsEntity
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-10-14T11:52:34.905+11:00")
public class ControllerBulletinsEntity {
  @SerializedName("bulletins")
  private List<BulletinEntity> bulletins = new ArrayList<BulletinEntity>();

  @SerializedName("controllerServiceBulletins")
  private List<BulletinEntity> controllerServiceBulletins = new ArrayList<BulletinEntity>();

  @SerializedName("reportingTaskBulletins")
  private List<BulletinEntity> reportingTaskBulletins = new ArrayList<BulletinEntity>();

  public ControllerBulletinsEntity bulletins(List<BulletinEntity> bulletins) {
    this.bulletins = bulletins;
    return this;
  }

  public ControllerBulletinsEntity addBulletinsItem(BulletinEntity bulletinsItem) {
    this.bulletins.add(bulletinsItem);
    return this;
  }

   /**
   * System level bulletins to be reported to the user.
   * @return bulletins
  **/
  @ApiModelProperty(example = "null", value = "System level bulletins to be reported to the user.")
  public List<BulletinEntity> getBulletins() {
    return bulletins;
  }

  public void setBulletins(List<BulletinEntity> bulletins) {
    this.bulletins = bulletins;
  }

  public ControllerBulletinsEntity controllerServiceBulletins(List<BulletinEntity> controllerServiceBulletins) {
    this.controllerServiceBulletins = controllerServiceBulletins;
    return this;
  }

  public ControllerBulletinsEntity addControllerServiceBulletinsItem(BulletinEntity controllerServiceBulletinsItem) {
    this.controllerServiceBulletins.add(controllerServiceBulletinsItem);
    return this;
  }

   /**
   * Controller service bulletins to be reported to the user.
   * @return controllerServiceBulletins
  **/
  @ApiModelProperty(example = "null", value = "Controller service bulletins to be reported to the user.")
  public List<BulletinEntity> getControllerServiceBulletins() {
    return controllerServiceBulletins;
  }

  public void setControllerServiceBulletins(List<BulletinEntity> controllerServiceBulletins) {
    this.controllerServiceBulletins = controllerServiceBulletins;
  }

  public ControllerBulletinsEntity reportingTaskBulletins(List<BulletinEntity> reportingTaskBulletins) {
    this.reportingTaskBulletins = reportingTaskBulletins;
    return this;
  }

  public ControllerBulletinsEntity addReportingTaskBulletinsItem(BulletinEntity reportingTaskBulletinsItem) {
    this.reportingTaskBulletins.add(reportingTaskBulletinsItem);
    return this;
  }

   /**
   * Reporting task bulletins to be reported to the user.
   * @return reportingTaskBulletins
  **/
  @ApiModelProperty(example = "null", value = "Reporting task bulletins to be reported to the user.")
  public List<BulletinEntity> getReportingTaskBulletins() {
    return reportingTaskBulletins;
  }

  public void setReportingTaskBulletins(List<BulletinEntity> reportingTaskBulletins) {
    this.reportingTaskBulletins = reportingTaskBulletins;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ControllerBulletinsEntity controllerBulletinsEntity = (ControllerBulletinsEntity) o;
    return Objects.equals(this.bulletins, controllerBulletinsEntity.bulletins) &&
        Objects.equals(this.controllerServiceBulletins, controllerBulletinsEntity.controllerServiceBulletins) &&
        Objects.equals(this.reportingTaskBulletins, controllerBulletinsEntity.reportingTaskBulletins);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bulletins, controllerServiceBulletins, reportingTaskBulletins);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ControllerBulletinsEntity {\n");
    
    sb.append("    bulletins: ").append(toIndentedString(bulletins)).append("\n");
    sb.append("    controllerServiceBulletins: ").append(toIndentedString(controllerServiceBulletins)).append("\n");
    sb.append("    reportingTaskBulletins: ").append(toIndentedString(reportingTaskBulletins)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

