/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ProvenanceLinkDTO;
import io.swagger.client.model.ProvenanceNodeDTO;
import java.util.ArrayList;
import java.util.List;

/**
 * LineageResultsDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-10-14T11:52:34.905+11:00")
public class LineageResultsDTO {
  @SerializedName("errors")
  private List<String> errors = new ArrayList<String>();

  @SerializedName("nodes")
  private List<ProvenanceNodeDTO> nodes = new ArrayList<ProvenanceNodeDTO>();

  @SerializedName("links")
  private List<ProvenanceLinkDTO> links = new ArrayList<ProvenanceLinkDTO>();

  public LineageResultsDTO errors(List<String> errors) {
    this.errors = errors;
    return this;
  }

  public LineageResultsDTO addErrorsItem(String errorsItem) {
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Any errors that occurred while generating the lineage.
   * @return errors
  **/
  @ApiModelProperty(example = "null", value = "Any errors that occurred while generating the lineage.")
  public List<String> getErrors() {
    return errors;
  }

  public void setErrors(List<String> errors) {
    this.errors = errors;
  }

  public LineageResultsDTO nodes(List<ProvenanceNodeDTO> nodes) {
    this.nodes = nodes;
    return this;
  }

  public LineageResultsDTO addNodesItem(ProvenanceNodeDTO nodesItem) {
    this.nodes.add(nodesItem);
    return this;
  }

   /**
   * The nodes in the lineage.
   * @return nodes
  **/
  @ApiModelProperty(example = "null", value = "The nodes in the lineage.")
  public List<ProvenanceNodeDTO> getNodes() {
    return nodes;
  }

  public void setNodes(List<ProvenanceNodeDTO> nodes) {
    this.nodes = nodes;
  }

  public LineageResultsDTO links(List<ProvenanceLinkDTO> links) {
    this.links = links;
    return this;
  }

  public LineageResultsDTO addLinksItem(ProvenanceLinkDTO linksItem) {
    this.links.add(linksItem);
    return this;
  }

   /**
   * The links between the nodes in the lineage.
   * @return links
  **/
  @ApiModelProperty(example = "null", value = "The links between the nodes in the lineage.")
  public List<ProvenanceLinkDTO> getLinks() {
    return links;
  }

  public void setLinks(List<ProvenanceLinkDTO> links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LineageResultsDTO lineageResultsDTO = (LineageResultsDTO) o;
    return Objects.equals(this.errors, lineageResultsDTO.errors) &&
        Objects.equals(this.nodes, lineageResultsDTO.nodes) &&
        Objects.equals(this.links, lineageResultsDTO.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errors, nodes, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LineageResultsDTO {\n");
    
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    nodes: ").append(toIndentedString(nodes)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

