/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * StatusDescriptorDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-10-14T11:52:34.905+11:00")
public class StatusDescriptorDTO {
  @SerializedName("field")
  private String field = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("formatter")
  private String formatter = null;

  public StatusDescriptorDTO field(String field) {
    this.field = field;
    return this;
  }

   /**
   * The name of the status field.
   * @return field
  **/
  @ApiModelProperty(example = "null", value = "The name of the status field.")
  public String getField() {
    return field;
  }

  public void setField(String field) {
    this.field = field;
  }

  public StatusDescriptorDTO label(String label) {
    this.label = label;
    return this;
  }

   /**
   * The label for the status field.
   * @return label
  **/
  @ApiModelProperty(example = "null", value = "The label for the status field.")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public StatusDescriptorDTO description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description of the status field.
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "The description of the status field.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public StatusDescriptorDTO formatter(String formatter) {
    this.formatter = formatter;
    return this;
  }

   /**
   * The formatter for the status descriptor.
   * @return formatter
  **/
  @ApiModelProperty(example = "null", value = "The formatter for the status descriptor.")
  public String getFormatter() {
    return formatter;
  }

  public void setFormatter(String formatter) {
    this.formatter = formatter;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatusDescriptorDTO statusDescriptorDTO = (StatusDescriptorDTO) o;
    return Objects.equals(this.field, statusDescriptorDTO.field) &&
        Objects.equals(this.label, statusDescriptorDTO.label) &&
        Objects.equals(this.description, statusDescriptorDTO.description) &&
        Objects.equals(this.formatter, statusDescriptorDTO.formatter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(field, label, description, formatter);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatusDescriptorDTO {\n");
    
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    formatter: ").append(toIndentedString(formatter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

