/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ComponentStateDTO;
import io.swagger.client.model.ProcessorEntity;
import io.swagger.client.model.PropertyDescriptorEntity;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProcessorsApi
 */
public class ProcessorsApiTest {

    private final ProcessorsApi api = new ProcessorsApi();

    
    /**
     * Clears the state for a processor
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void clearStateTest() throws ApiException {
        String id = null;
        // ComponentStateDTO response = api.clearState(id);

        // TODO: test validations
    }
    
    /**
     * Deletes a processor
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteProcessorTest() throws ApiException {
        String id = null;
        String version = null;
        String clientId = null;
        // ProcessorEntity response = api.deleteProcessor(id, version, clientId);

        // TODO: test validations
    }
    
    /**
     * Gets a processor
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProcessorTest() throws ApiException {
        String id = null;
        // ProcessorEntity response = api.getProcessor(id);

        // TODO: test validations
    }
    
    /**
     * Gets the descriptor for a processor property
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPropertyDescriptorTest() throws ApiException {
        String id = null;
        String propertyName = null;
        String clientId = null;
        // PropertyDescriptorEntity response = api.getPropertyDescriptor(id, propertyName, clientId);

        // TODO: test validations
    }
    
    /**
     * Gets the state for a processor
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStateTest() throws ApiException {
        String id = null;
        // ComponentStateDTO response = api.getState(id);

        // TODO: test validations
    }
    
    /**
     * Updates a processor
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateProcessorTest() throws ApiException {
        String id = null;
        ProcessorEntity body = null;
        // ProcessorEntity response = api.updateProcessor(id, body);

        // TODO: test validations
    }
    
}
